### ISSUE TITLE
Demo does no work

### ISSUE THREAD

**Issue by zhekaus** [Malikmal/Vue-MQTT-NodeMCU#1]
All I see on the link is a blank page.

**Comment by Malikmal** [comment]
@zhekaus 
Sorry for the existing domain is not active with https
so you can access without https 
http://malikmal98.ce.student.pens.ac.id/Vue-MQTT-NodeMCU/#/
![image](https://user-images.githubusercontent.com/36214726/187072516-bf5d4325-822e-4c2d-835e-67487e8e820f.png)


its only work for web ui interactivity not integrated with devices. if you want to see how it works with devices you can see the video on youtube as i write at readme

thank you
